# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mannumseq.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DManNumSeq(object):
    def setupUi(self, DManNumSeq):
        DManNumSeq.setObjectName("DManNumSeq")
        DManNumSeq.setEnabled(True)
        DManNumSeq.resize(472, 462)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DManNumSeq.setWindowIcon(icon)
        self.labelQttBits = QtWidgets.QLabel(DManNumSeq)
        self.labelQttBits.setGeometry(QtCore.QRect(50, 230, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelQttBits.setFont(font)
        self.labelQttBits.setObjectName("labelQttBits")
        self.checkBoxRemChar = QtWidgets.QCheckBox(DManNumSeq)
        self.checkBoxRemChar.setGeometry(QtCore.QRect(220, 140, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxRemChar.setFont(font)
        self.checkBoxRemChar.setChecked(False)
        self.checkBoxRemChar.setObjectName("checkBoxRemChar")
        self.labelSeparator = QtWidgets.QLabel(DManNumSeq)
        self.labelSeparator.setGeometry(QtCore.QRect(50, 200, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelSeparator.setFont(font)
        self.labelSeparator.setObjectName("labelSeparator")
        self.pushButtonGenNewFile = QtWidgets.QPushButton(DManNumSeq)
        self.pushButtonGenNewFile.setGeometry(QtCore.QRect(150, 410, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonGenNewFile.setFont(font)
        self.pushButtonGenNewFile.setObjectName("pushButtonGenNewFile")
        self.labelOldFilePath = QtWidgets.QLabel(DManNumSeq)
        self.labelOldFilePath.setGeometry(QtCore.QRect(10, 10, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelOldFilePath.setFont(font)
        self.labelOldFilePath.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.labelOldFilePath.setWordWrap(True)
        self.labelOldFilePath.setObjectName("labelOldFilePath")
        self.checkBoxBin = QtWidgets.QCheckBox(DManNumSeq)
        self.checkBoxBin.setGeometry(QtCore.QRect(20, 140, 161, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxBin.setFont(font)
        self.checkBoxBin.setObjectName("checkBoxBin")
        self.labelOldPathFile = QtWidgets.QLabel(DManNumSeq)
        self.labelOldPathFile.setGeometry(QtCore.QRect(20, 60, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelOldPathFile.setFont(font)
        self.labelOldPathFile.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.labelOldPathFile.setWordWrap(True)
        self.labelOldPathFile.setObjectName("labelOldPathFile")
        self.lineEditOldFilePath = QtWidgets.QLineEdit(DManNumSeq)
        self.lineEditOldFilePath.setGeometry(QtCore.QRect(10, 90, 451, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditOldFilePath.setFont(font)
        self.lineEditOldFilePath.setText("")
        self.lineEditOldFilePath.setObjectName("lineEditOldFilePath")
        self.line_2 = QtWidgets.QFrame(DManNumSeq)
        self.line_2.setGeometry(QtCore.QRect(10, 120, 451, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineEditQttBits = QtWidgets.QLineEdit(DManNumSeq)
        self.lineEditQttBits.setEnabled(False)
        self.lineEditQttBits.setGeometry(QtCore.QRect(300, 230, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditQttBits.setFont(font)
        self.lineEditQttBits.setObjectName("lineEditQttBits")
        self.lineEditRemChar = QtWidgets.QLineEdit(DManNumSeq)
        self.lineEditRemChar.setEnabled(False)
        self.lineEditRemChar.setGeometry(QtCore.QRect(350, 140, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditRemChar.setFont(font)
        self.lineEditRemChar.setObjectName("lineEditRemChar")
        self.checkBoxSep = QtWidgets.QCheckBox(DManNumSeq)
        self.checkBoxSep.setEnabled(True)
        self.checkBoxSep.setGeometry(QtCore.QRect(20, 170, 171, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxSep.setFont(font)
        self.checkBoxSep.setAcceptDrops(False)
        self.checkBoxSep.setAutoFillBackground(False)
        self.checkBoxSep.setChecked(False)
        self.checkBoxSep.setObjectName("checkBoxSep")
        self.lineEditSeparator = QtWidgets.QLineEdit(DManNumSeq)
        self.lineEditSeparator.setEnabled(False)
        self.lineEditSeparator.setGeometry(QtCore.QRect(120, 200, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditSeparator.setFont(font)
        self.lineEditSeparator.setObjectName("lineEditSeparator")
        self.lineEditInfo = QtWidgets.QLineEdit(DManNumSeq)
        self.lineEditInfo.setGeometry(QtCore.QRect(10, 350, 451, 20))
        self.lineEditInfo.setObjectName("lineEditInfo")
        self.labelInfo = QtWidgets.QLabel(DManNumSeq)
        self.labelInfo.setGeometry(QtCore.QRect(10, 270, 451, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.labelInfo.setFont(font)
        self.labelInfo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelInfo.setTextFormat(QtCore.Qt.AutoText)
        self.labelInfo.setScaledContents(False)
        self.labelInfo.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.labelInfo.setWordWrap(True)
        self.labelInfo.setObjectName("labelInfo")
        self.line = QtWidgets.QFrame(DManNumSeq)
        self.line.setGeometry(QtCore.QRect(10, 260, 451, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.labelQttBits.setBuddy(self.lineEditQttBits)
        self.labelSeparator.setBuddy(self.lineEditSeparator)
        self.labelOldPathFile.setBuddy(self.lineEditOldFilePath)
        self.labelInfo.setBuddy(self.lineEditInfo)

        self.retranslateUi(DManNumSeq)
        self.checkBoxRemChar.clicked['bool'].connect(self.lineEditRemChar.setEnabled)
        self.checkBoxSep.clicked['bool'].connect(self.lineEditSeparator.setEnabled)
        self.checkBoxSep.clicked['bool'].connect(self.lineEditQttBits.setEnabled)
        self.pushButtonGenNewFile.clicked.connect(DManNumSeq.close)
        QtCore.QMetaObject.connectSlotsByName(DManNumSeq)
        DManNumSeq.setTabOrder(self.lineEditOldFilePath, self.lineEditQttBits)
        DManNumSeq.setTabOrder(self.lineEditQttBits, self.checkBoxRemChar)
        DManNumSeq.setTabOrder(self.checkBoxRemChar, self.lineEditRemChar)
        DManNumSeq.setTabOrder(self.lineEditRemChar, self.checkBoxBin)
        DManNumSeq.setTabOrder(self.checkBoxBin, self.checkBoxSep)
        DManNumSeq.setTabOrder(self.checkBoxSep, self.lineEditSeparator)
        DManNumSeq.setTabOrder(self.lineEditSeparator, self.pushButtonGenNewFile)

    def retranslateUi(self, DManNumSeq):
        _translate = QtCore.QCoreApplication.translate
        DManNumSeq.setWindowTitle(_translate("DManNumSeq", "Manipulate Number Sequence"))
        self.labelQttBits.setText(_translate("DManNumSeq", "Quantity of numbers between separators:"))
        self.checkBoxRemChar.setText(_translate("DManNumSeq", "Erase a character:"))
        self.labelSeparator.setText(_translate("DManNumSeq", "Separator:"))
        self.pushButtonGenNewFile.setText(_translate("DManNumSeq", "Generate New File!"))
        self.labelOldFilePath.setText(_translate("DManNumSeq", "This code is made to alter the numbers\' disposition in a integer-only sequence text file. This file has to be located in a subfolder of /Output/txtoutput/.  "))
        self.checkBoxBin.setText(_translate("DManNumSeq", "Set Numbers To Binary"))
        self.labelOldPathFile.setText(_translate("DManNumSeq", "Text File Path: (ex: /fromimg/Elementary/30.txt )"))
        self.checkBoxSep.setText(_translate("DManNumSeq", "Insert Numbers Separator"))
        self.labelInfo.setText(_translate("DManNumSeq", "The text file with the new sequence of numbers will be saved in \" /Output/txtoutput/treated/(automaton\'s type)/ (rule).txt \". If there is another file with the same name in this folder, it will be overwritten. If you want to add some information to the file name, type it below:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DManNumSeq = QtWidgets.QDialog()
    ui = Ui_DManNumSeq()
    ui.setupUi(DManNumSeq)
    DManNumSeq.show()
    sys.exit(app.exec_())

